
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftTIMESDIVIDErightUMINUSABS DIVIDE EXP LPAREN MINUS NUMBER PLUS RPAREN SQRT TIMES\nexpression : expression PLUS expression\n           | expression MINUS expression\n           | expression TIMES expression\n           | expression DIVIDE expression\nexpression : LPAREN expression RPARENexpression : NUMBERexpression : MINUS expression %prec UMINUSexpression : ABS LPAREN expression RPARENexpression : SQRT LPAREN expression RPARENexpression : EXP LPAREN expression RPAREN'
    
_lr_action_items = {'LPAREN':([0,2,3,5,6,7,8,9,10,11,14,15,16,],[3,3,3,14,15,16,3,3,3,3,3,3,3,]),'NUMBER':([0,2,3,8,9,10,11,14,15,16,],[4,4,4,4,4,4,4,4,4,4,]),'MINUS':([0,1,2,3,4,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,],[2,9,2,2,-6,2,2,2,2,-7,9,2,2,2,-1,-2,-3,-4,-5,9,9,9,-8,-9,-10,]),'ABS':([0,2,3,8,9,10,11,14,15,16,],[5,5,5,5,5,5,5,5,5,5,]),'SQRT':([0,2,3,8,9,10,11,14,15,16,],[6,6,6,6,6,6,6,6,6,6,]),'EXP':([0,2,3,8,9,10,11,14,15,16,],[7,7,7,7,7,7,7,7,7,7,]),'$end':([1,4,12,17,18,19,20,21,25,26,27,],[0,-6,-7,-1,-2,-3,-4,-5,-8,-9,-10,]),'PLUS':([1,4,12,13,17,18,19,20,21,22,23,24,25,26,27,],[8,-6,-7,8,-1,-2,-3,-4,-5,8,8,8,-8,-9,-10,]),'TIMES':([1,4,12,13,17,18,19,20,21,22,23,24,25,26,27,],[10,-6,-7,10,10,10,-3,-4,-5,10,10,10,-8,-9,-10,]),'DIVIDE':([1,4,12,13,17,18,19,20,21,22,23,24,25,26,27,],[11,-6,-7,11,11,11,-3,-4,-5,11,11,11,-8,-9,-10,]),'RPAREN':([4,12,13,17,18,19,20,21,22,23,24,25,26,27,],[-6,-7,21,-1,-2,-3,-4,-5,25,26,27,-8,-9,-10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,8,9,10,11,14,15,16,],[1,12,13,17,18,19,20,22,23,24,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS expression','expression',3,'p_expression_binop','parser.py',26),
  ('expression -> expression MINUS expression','expression',3,'p_expression_binop','parser.py',27),
  ('expression -> expression TIMES expression','expression',3,'p_expression_binop','parser.py',28),
  ('expression -> expression DIVIDE expression','expression',3,'p_expression_binop','parser.py',29),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','parser.py',43),
  ('expression -> NUMBER','expression',1,'p_expression_number','parser.py',47),
  ('expression -> MINUS expression','expression',2,'p_expression_uminus','parser.py',51),
  ('expression -> ABS LPAREN expression RPAREN','expression',4,'p_expression_abs','parser.py',55),
  ('expression -> SQRT LPAREN expression RPAREN','expression',4,'p_expression_sqrt','parser.py',59),
  ('expression -> EXP LPAREN expression RPAREN','expression',4,'p_expression_exp','parser.py',65),
]
